export const TABLE_CELL_SIZE = 64;
export const SELECTED_CELL_SIZE = 150;
export const SELECTED_CELL_SCALE = SELECTED_CELL_SIZE / TABLE_CELL_SIZE;

export const HISTORY_CELL_SIZE = 26;
export const HISTORY_VISIBLE_COUNT = 10;
export const HISTORY_GAP = 2;
export const HISTORY_CONTAINER_WIDTH =
  HISTORY_VISIBLE_COUNT * HISTORY_CELL_SIZE + (HISTORY_VISIBLE_COUNT - 1) * HISTORY_GAP;
export const HISTORY_JAUGE_HEIGHT = 20;
export const HISTORY_JAUGE_WIDTH = 8;
